### ISSUE TITLE
Update Spring Boot layered jar support

### ISSUE THREAD

**Issue by nebhale** [paketo-buildpacks/spring-boot#1]
via @philwebb

We found quite a few problems with the layered jar format so we changed direction quite late in the day. We now have a meta-data file instead of a an updated structure.

The fix #6 will probably need to be updated. The new format has now been documented here: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#executable-jar-war-index-files

[This Go code](https://gist.github.com/philwebb/e61287f9770844548e29f12dce252328) might also be useful. I used it to test that the `layer.idx` file can be loaded as YAML.

**Comment by nebhale** [comment]
Supersedes cloudfoundry/spring-boot-cnb#9.

**Comment by Decat-SimonA** [comment]
It looks like the docker image still contains a single layer with app+all dependencies.
Has this been fixed recently ?

**Comment by Decat-SimonA** [comment]
Oh my bad, I forgot that [layeredJar](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/gradle-plugin/reference/html/#packaging-layered-jars) is opt-in :disappointed: 

After enabling it, everything works perfectly, thanks !

**Comment by lzimd** [comment]
That reason is [`filepath.Rel` and `filepath.Match` in `func glob(sdir *sliceableDir, pattern string) ([]string, error)`](https://github.com/buildpacks/lifecycle/blob/v0.9.2/layers/slices.go#L80).

eg. `filepath.Rel` return `BOOT-INF/lib`, `filepath.Match` return false against `BOOT-INF/lib/`, so app layers 1~4 are almost empty.


That is spring-boot's `layers.idx`.

```yaml
- "dependencies":
  - "BOOT-INF/lib/"
- "spring-boot-loader":
  - "org/"
- "snapshot-dependencies":
- "application":
  - "BOOT-INF/classes/"
  - "BOOT-INF/classpath.idx"
  - "BOOT-INF/layers.idx"
  - "META-INF/"
```
