### ISSUE TITLE
Add Actuator client for Docker HEALTHCHECK 

### ISSUE THREAD

**Issue by emersonf** [paketo-buildpacks/spring-boot#168]
This is just a feature request, so not sure the default template applies. 

## Feature request
I'd like to set up a Docker [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) for a Spring Boot app running Spring Boot Actuator. Using the default Liberica JRE, `curl` isn't present, so something like the following fails:

```
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health-check"]
      interval: 5s
      timeout: 2s
      start_period: 15s
      retries: 20
```      

I thought "I guess I'll write a buildpack with some lightweight HTTP client in Java that I can reference from `test:`", as [explained nicely in this blog post](https://mflash.dev/blog/2021/03/01/java-based-health-check-for-docker/). And then thought "Wait, I'm already using a Spring Boot buildpack, is this a regular enough use case for it to be included with the Spring Boot buildpack itself?" 🙂
